export { InstructorDashboardPage } from './InstructorDashboardPage'
export { CourseFormPage } from './CourseFormPage'
export { ModulesManagementPage } from './ModulesManagementPage'
export { LessonFormPage } from './LessonFormPage'
export { AssessmentsManagementPage } from './AssessmentsManagementPage'
export { GradingPage } from './GradingPage'
export { CourseStudentsPage } from './CourseStudentsPage'
